version: "3"
services:
  adjectives-api:
    build: 
      context: ./backend/adjectives-api
    image: adjectives-api-image
    container_name: adjectives-server
    ports:
      - "5001:5001"
    env_file:
      - .backend/adjectives-api/.env
    networks:
      - my-net
  cities-api:
    build: 
      context: ./backend/cities-api
    image: cities-api-image
    container_name: cities-server
    ports:
      - "5002:5002"
    env_file:
      - .backend/adjectives-api/.env
    networks:
      - my-net
  frontend:
    build: 
      context: ./frontend
    image: frontend-image
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - adjectives-api
      - cities-api
    networks:
      - my-net
  nginx:
    build: 
      context: ./nginx
    image: nginx-image
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./nginx/certbot/www:/var/www/certbot/:ro
      - ./nginx/certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - frontend
    networks:
      - my-net
  certbot:
    build: 
      context: ./nginx/certbot
    image: certbot-image
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./nginx/certbot/www/:/var/www/certbot/:rw
      - ./nginx/certbot/conf/:/etc/letsencrypt/:rw
    depends_on:
      - nginx
    networks:
      - my-net
networks:
  my-net:
     external: true
