version: '3'
services:
  webserver:
    image: nginx-image
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./nginx/certbot/www:/var/www/certbot/:ro
  certbot:
    image: certbot-image
    volumes:
      - ./nginx/certbot/www/:/var/www/certbot/:rw